api_platform:
    mapping:
        paths:
            - '%bounded_context_root_path%/App/Api/Resource'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
