framework:
    messenger:
        failure_transport: failed

        transports:
            query: 'sync://'        # transport synchrone
            command:                # transport Asynchrone
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/command'
                retry_strategy:
                    max_retries: 3
            failed: '%env(MESSENGER_TRANSPORT_DSN)%/failed'

        routing:
            App\Domain\Stakeholder\Command\Message\RegisterAUserMessage: command
            App\Domain\Stakeholder\Query\Message\FetchUserMessage: query
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
